---
name: pyrefly
description: Pyrefly is a type checker
homepage: https://github.com/facebook/pyrefly
licenses:
  - MIT
languages:
  - Python
categories:
  - Linter
  - LSP

schemas:
  lsp: vscode:https://raw.githubusercontent.com/facebook/pyrefly/{{version}}/lsp/package.json

source:
  id: pkg:pypi/pyrefly@0.15.2

bin:
  ty: pypi:pyrefly

neovim:
  lspconfig: pyrefly
